### ISSUE TITLE
Loading multiple Surfaces/GL.Nodes simultaneously, using the same shader, sometimes causes an exception on Android

### ISSUE THREAD

**Issue by IjzerenHein** [ProjectSeptemberInc/gl-react-native#150]
Hi, I'm running into an exception which happens occasionally.

I have two views which are both rendered/mounted at exactly the same time. Both views contain a Surface with a single GL.Node, which uses the same shader.

Effectively this:

```
...
<Surface width={width} height={height} style={StyleSheet.absoluteFill} backgroundColor='#000000'>
   <GL.Node
	backgroundColor='#000000'
	shader={shaders.feet}
	uniforms={{
		dim: [width, height],
		left: left
	}} />
</Surface>
...
<Surface width={width} height={height} style={StyleSheet.absoluteFill} backgroundColor='#000000'>
   <GL.Node
	backgroundColor='#000000'
	shader={shaders.feet}
	uniforms={{
		dim: [width, height],
		left: left
	}} />
</Surface>
...
```

This seems to cause a crash every now and them, which seems timing related. 
Here are the crash logs:

```
03-30 18:58:53.525 7436-9079/com.atogear.arion E/UncaughtException: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
                                                                        at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:32)
                                                                        at com.projectseptember.RNGL.RNGLContext.shaderSucceedToCompile(RNGLContext.java:82)
                                                                        at com.projectseptember.RNGL.GLShader.ensureCompile(GLShader.java:243)
                                                                        at com.projectseptember.RNGL.GLCanvas.recSyncData(GLCanvas.java:450)
                                                                        at com.projectseptember.RNGL.GLCanvas.syncData(GLCanvas.java:762)
                                                                        at com.projectseptember.RNGL.GLCanvas.access$100(GLCanvas.java:49)
                                                                        at com.projectseptember.RNGL.GLCanvas$2.run(GLCanvas.java:322)
                                                                        at com.projectseptember.RNGL.GLCanvas.runAll(GLCanvas.java:312)
                                                                        at com.projectseptember.RNGL.GLCanvas.onDrawFrame(GLCanvas.java:144)
                                                                        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
                                                                        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
03-30 18:58:53.528 7436-7531/com.atogear.arion I/FA: Tag Manager is not found and thus will not be used
03-30 18:58:53.554 7436-8402/com.atogear.arion D/ReactNativeJS: Set succesful, reading status...
03-30 18:58:53.561 7436-8402/com.atogear.arion D/ReactNativeJS: Set succesful, reading status...
03-30 18:58:53.795 7436-9079/com.atogear.arion E/AndroidRuntime: FATAL EXCEPTION: GLThread 30452
                                                                 Process: com.atogear.arion, PID: 7436
                                                                 java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
                                                                     at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:32)
                                                                     at com.projectseptember.RNGL.RNGLContext.shaderSucceedToCompile(RNGLContext.java:82)
                                                                     at com.projectseptember.RNGL.GLShader.ensureCompile(GLShader.java:243)
                                                                     at com.projectseptember.RNGL.GLCanvas.recSyncData(GLCanvas.java:450)
                                                                     at com.projectseptember.RNGL.GLCanvas.syncData(GLCanvas.java:762)
                                                                     at com.projectseptember.RNGL.GLCanvas.access$100(GLCanvas.java:49)
                                                                     at com.projectseptember.RNGL.GLCanvas$2.run(GLCanvas.java:322)
                                                                     at com.projectseptember.RNGL.GLCanvas.runAll(GLCanvas.java:312)
                                                                     at com.projectseptember.RNGL.GLCanvas.onDrawFrame(GLCanvas.java:144)
                                                                     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
                                                                     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```

Do you have any idea where the problem could be?

cheers, Hein

**Comment by IjzerenHein** [comment]
Not sure if this is the problem or related, but I noticed that RNGLContext.shaderFailedToCompile is missing `onCompileCallbacks.remove(id)`

Original code:
```
public void shaderFailedToCompile(Integer id, GLShaderCompilationFailed e) {
        Callback onCompile = onCompileCallbacks.get(id);
        if (onCompile == null) {
            Log.e("RNGLContext", e.getMessage());
        }
        else {
            onCompile.invoke(e.compileError);
        }
    }

    public void shaderSucceedToCompile(Integer id, Map<String, Integer> uniformTypes) {
        Callback onCompile = onCompileCallbacks.get(id);
        onCompileCallbacks.remove(id);
        if (onCompile != null) {
            WritableMap res = Arguments.createMap();
            WritableMap uniforms = Arguments.createMap();
            for (String key : uniformTypes.keySet()) {
                uniforms.putString(key, glTypeString(uniformTypes.get(key)));
            }
            res.putMap("uniforms", uniforms);
            onCompile.invoke(null, res);
        }
    }
```

**Comment by timCF** [comment]
+1
Have the same problem. With 1 surface it works nice, but when there are 2 or more - app crashes :(

**Comment by kesha-antonov** [comment]
+1

Did you solve this?

**Comment by IjzerenHein** [comment]
I'm also still experiencing this

**Comment by IjzerenHein** [comment]
I quite regularly see this issue, here's another example of the crash log:

```
com.facebook.react.bridge.CallbackImpl.invoke (CallbackImpl.java:30)
com.projectseptember.RNGL.RNGLContext.shaderSucceedToCompile (RNGLContext.java:82)
com.projectseptember.RNGL.GLShader.ensureCompile (GLShader.java:243)
com.projectseptember.RNGL.GLCanvas.recSyncData (GLCanvas.java:450)
com.projectseptember.RNGL.GLCanvas.syncData (GLCanvas.java:762)
com.projectseptember.RNGL.GLCanvas.access$100 (GLCanvas.java:49)
com.projectseptember.RNGL.GLCanvas$2.run (GLCanvas.java:322)
com.projectseptember.RNGL.GLCanvas.runAll (GLCanvas.java:312)
com.projectseptember.RNGL.GLCanvas.onDrawFrame (GLCanvas.java:144)
android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1522)
android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1239)
```

**Comment by IjzerenHein** [comment]
Hi, I've been debugging this issue and have some results.

I've extended `GLShader.java` with some Log statements, like this:

```java
public boolean ensureCompile() {
        boolean ready = isReady();
        Log.i("GLShader", "ensureCompile.thread: " + Thread.currentThread().getName() + ", ready: " + ready + ", id: " + id);

        if (!ready) {
            if (compilationFailed != null) throw compilationFailed;
            try {
                Log.i("GLShader", "ensureCompile.thread: " + Thread.currentThread().getName() + ", id: " + id + ", compiling...");
                makeProgram();
                rnglContext.shaderSucceedToCompile(id, uniformTypes);
                Log.i("GLShader", "ensureCompile.thread: " + Thread.currentThread().getName() + ", id: " + id + ", compiling... DONE");
            }
            catch (GLShaderCompilationFailed e) {
                compilationFailed = e;
                rnglContext.shaderFailedToCompile(id, e);
                throw e;
            }
        }
        return isReady();
    }
```

And when inspecting the log, I see this:

```
12-14 18:40:14.284 5543-5628/? I/GLShader: ensureCompile.thread: GLThread 2450, ready: false, id: 1
12-14 18:40:14.284 5543-5628/? I/GLShader: ensureCompile.thread: GLThread 2450, id: 1, compiling...
12-14 18:40:14.287 5543-5627/? I/GLShader: ensureCompile.thread: GLThread 2449, ready: false, id: 1
12-14 18:40:14.289 5543-5627/? I/GLShader: ensureCompile.thread: GLThread 2449, id: 1, compiling...
12-14 18:40:14.319 5543-5628/? I/GLShader: ensureCompile.thread: GLThread 2450, id: 1, compiling... DONE
12-14 18:40:14.319 5543-5628/? I/GLShader: ensureCompile.thread: GLThread 2450, ready: false, id: 2
12-14 18:40:14.320 5543-5628/? I/GLShader: ensureCompile.thread: GLThread 2450, id: 2, compiling...
12-14 18:40:14.324 5543-5627/? I/GLShader: ensureCompile.thread: GLThread 2449, id: 1, compiling... DONE
12-14 18:40:14.324 5543-5627/? I/GLShader: ensureCompile.thread: GLThread 2449, ready: false, id: 2
12-14 18:40:14.324 5543-5627/? I/GLShader: ensureCompile.thread: GLThread 2449, id: 2, compiling...
12-14 18:40:14.353 5543-5628/? I/GLShader: ensureCompile.thread: GLThread 2450, id: 2, compiling... DONE
12-14 18:40:14.353 5543-5627/? I/GLShader: ensureCompile.thread: GLThread 2449, id: 2, compiling... DONE
12-14 18:40:14.371 5543-5628/? I/GLShader: ensureCompile.thread: GLThread 2450, ready: true, id: 1
12-14 18:40:14.371 5543-5628/? I/GLShader: ensureCompile.thread: GLThread 2450, ready: true, id: 2
12-14 18:40:14.372 5543-5627/? I/GLShader: ensureCompile.thread: GLThread 2449, ready: true, id: 1
12-14 18:40:14.372 5543-5627/? I/GLShader: ensureCompile.thread: GLThread 2449, ready: true, id: 2
12-14 18:40:14.373 5543-5627/? I/GLShader: ensureCompile.thread: GLThread 2449, ready: true, id: 1
12-14 18:40:14.373 5543-5627/? I/GLShader: ensureCompile.thread: GLThread 2449, ready: true, id: 2
```

From the log you can clearly see that the shader is compiled multiple times, by two different threads.

This is how my render method looks like:

```js
        <View style={styles.row}>
          <Surface style={styles.cell} width={WIDTH} height={HEIGHT}>
            <GL.Node
              shader={shaders.feet}
              uniforms={{
                dim: [WIDTH, HEIGHT],
                backColor: BACK_COLOR,
                image: IMAGE_SOURCE.left,
                left: true,
                samples: [0, 0, 0, 0, 0, 0, 0, 0],
              }} />
          </Surface>
          <Surface style={styles.cell} width={WIDTH} height={HEIGHT}>
            <GL.Node
              shader={shaders.feet}
              uniforms={{
                dim: [WIDTH, HEIGHT],
                backColor: BACK_COLOR,
                image: IMAGE_SOURCE.right,
                left: false,
                samples: [0, 0, 0, 0, 0, 0, 0, 0],
              }} />
          </Surface>
        </View>
}
```

You can find the [full React Component here](https://gist.github.com/IjzerenHein/b8071cb3cd246edda95a2048b3a2a322)

There is clearly something wrong here. I'm gonna investigate further and see whether I can come up with a solution. @gre if you have any feedback or comments on how to adres this let me know. Cheers

**Comment by IjzerenHein** [comment]
Alright, after further inspection and debugging, I've come to the conclusion that the problem is not in the `GLShader` class, but in the `RNGLContext` class. This class is not thread-safe, but is accessed by multiple threads at the same time (multiple GL threads & RN threads). The problem comes down to `shaderSucceedToCompile` which is called whenever each GLCanvas finished compiling its shader. However, when you have multiple Surfaces that use the same shader, this function is called multiple times with the same `id`. In the unlucky event, there is a thread-switch in this location, the mentioned exception occurs.

```java
    public void shaderSucceedToCompile(Integer id, Map<String, Integer> uniformTypes) {
        Callback onCompile = onCompileCallbacks.get(id);
>>> exception occurs when there is a thread-switch at this location <<<
        onCompileCallbacks.remove(id);
        if (onCompile != null) {
            WritableMap res = Arguments.createMap();
            WritableMap uniforms = Arguments.createMap();
            for (String key : uniformTypes.keySet()) {
                uniforms.putString(key, glTypeString(uniformTypes.get(key)));
            }
            res.putMap("uniforms", uniforms);
            onCompile.invoke(null, res);
        }
    }
```

**Comment by IjzerenHein** [comment]
Created PR #175 for this.
