### ISSUE TITLE
run android, Can run, but will crash after a while

### ISSUE THREAD

**Issue by jlala** [ProjectSeptemberInc/gl-react-native#191]
gl-react-native-v2

#### library version
react-native:0.57.4

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.projectseptember.RNGL.GLCanvas.recSyncData(GLCanvas.java:479)
        at com.projectseptember.RNGL.GLCanvas.recSyncData(GLCanvas.java:466)
        at com.projectseptember.RNGL.GLCanvas.syncData(GLCanvas.java:762)
        at com.projectseptember.RNGL.GLCanvas.access$100(GLCanvas.java:49)
        at com.projectseptember.RNGL.GLCanvas$2.run(GLCanvas.java:322)
        at com.projectseptember.RNGL.GLCanvas.runAll(GLCanvas.java:312)
        at com.projectseptember.RNGL.GLCanvas.onDrawFrame(GLCanvas.java:144)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1599)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1295)

**Comment by jlala** [comment]
I have used the same two <Surface/>
