### ISSUE TITLE
Android crash on capture with react-native-image-cropper

### ISSUE THREAD

**Issue by juniorneo2** [ProjectSeptemberInc/gl-react-native#199]
I'm using a plugin to crop the image and in the android version crashing is occurring.

Plugin : https://github.com/stoffern/react-native-image-cropper
package.json
 "gl-react-native": "^2.47.0"
 "react-native": "^0.59.6"
 "react-native-image-cropper": "^0.4.5",

`Exception in native call
    java.lang.IllegalArgumentException: Could not find @ReactModule annotation in com.projectseptember.RNGL.RNGLContext
        at com.facebook.react.bridge.CatalystInstanceImpl.getNameFromAnnotation(CatalystInstanceImpl.java:438)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:427)
        at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:128)
        at com.projectseptember.RNGL.GLCanvas.<init>(GLCanvas.java:84)
        at com.projectseptember.RNGL.GLCanvasManager.createViewInstance(GLCanvasManager.java:95)
        at com.projectseptember.RNGL.GLCanvasManager.createViewInstance(GLCanvasManager.java:22)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:47)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:256)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1109)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1080)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:618)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by derdawid** [comment]
Same happened to me. I don't use react-native-image-cropper but had the same problem.
In my case I upgrade from RN 57 to 59. 

Seems it's fixed and merged, but not yet released. 

update package.json
```
        "gl-react": "v2.3.1",
        "gl-react-native": "git://github.com/gre/gl-react-native-v2.git#10d3dce593080301dc12e467cd5e1c3d22995167",
```
